package com.pangge.moontest;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WEATHER".
 */
@Entity
public class Weather {

    @Id
    private Long id;
    private String date;
    private String type;
    private String high;
    private String low;
    private String fengxiang;
    private String fengli;
    private String city;
    private String wendu;
    private String ganmao;

    @Generated
    public Weather() {
    }

    public Weather(Long id) {
        this.id = id;
    }

    @Generated
    public Weather(Long id, String date, String type, String high, String low, String fengxiang, String fengli, String city, String wendu, String ganmao) {
        this.id = id;
        this.date = date;
        this.type = type;
        this.high = high;
        this.low = low;
        this.fengxiang = fengxiang;
        this.fengli = fengli;
        this.city = city;
        this.wendu = wendu;
        this.ganmao = ganmao;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getHigh() {
        return high;
    }

    public void setHigh(String high) {
        this.high = high;
    }

    public String getLow() {
        return low;
    }

    public void setLow(String low) {
        this.low = low;
    }

    public String getFengxiang() {
        return fengxiang;
    }

    public void setFengxiang(String fengxiang) {
        this.fengxiang = fengxiang;
    }

    public String getFengli() {
        return fengli;
    }

    public void setFengli(String fengli) {
        this.fengli = fengli;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getWendu() {
        return wendu;
    }

    public void setWendu(String wendu) {
        this.wendu = wendu;
    }

    public String getGanmao() {
        return ganmao;
    }

    public void setGanmao(String ganmao) {
        this.ganmao = ganmao;
    }

}
